on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      # to avoid the diskspace error
      - name: free disk space
        run: |
          sudo swapoff -a
          sudo rm -f /swapfile
          sudo apt clean
          docker rmi $(docker image ls -aq)
          df -h
        
      - name: Checkout
        uses: actions/checkout@v4
        
      # your build step here
        
      - name: deploy2nekoweb
        uses: deploy2nekoweb/deploy2nekoweb@v4
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-folder: '/tyoma.cool'
          directory: '/'

