on: [push]
name: My build action requiring more space
on: push

jobs:
  build:
      name: Build my artifact
      runs-on: ubuntu-latest
      steps:
        - name: Maximize build space
          uses: easimon/maximize-build-space@master
          with:
            root-reserve-mb: 512
            swap-size-mb: 1024
            remove-dotnet: 'true'
        - name: Checkout
          uses: actions/checkout@v3
  
        - name: Build
          run: |
            echo "Free space:"
            df -h
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      # your build step here
        
      - name: deploy2nekoweb
        uses: deploy2nekoweb/deploy2nekoweb@v4
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-folder: '/tyoma.cool'
          directory: '/'

