on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    name: deploy2nekoweb
    steps:
      - name: Free Disk Space (Ubuntu)
      # You may pin to the exact commit or the version.
      # uses: jlumbroso/free-disk-space@54081f138730dfa15788a46383842cd2f914a1be
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          # Remove Android runtime
          android: # optional, default is true
          # Remove .NET runtime
          dotnet: # optional, default is true
          # Remove Haskell runtime
          haskell: # optional, default is true
          # Remove large packages
          large-packages: # optional, default is true
          # Remove Docker images
          docker-images: # optional, default is true
          # Remove image tool cache
          tool-cache: # optional, default is false
          # Remove swap storage
          swap-storage: # optional, default is true
          
      - name: Checkout
        uses: actions/checkout@v4
        
      # your build step here
        
      - name: deploy2nekoweb
        uses: deploy2nekoweb/deploy2nekoweb@v4
        with:
          nekoweb-api-key: ${{ secrets.NEKOWEB_API_KEY }}
          nekoweb-cookie: ${{ secrets.NEKOWEB_COOKIE }}
          nekoweb-folder: '/tyoma.cool'
          directory: '/'

